[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
forge = "J6tbrmGmpQ7bskpUB2DXcjjDp4VwVs78haXQ7FqZ1CUi"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
